minwareco/tap-github

tap_github/__init__.py, tap_github/schemas/commits.json
Updated tap to fetch raw contents before/after for missing matches for large changes, and then recreate patches for those changes. Note: this doesn't update PR commits, which are going to become shallower in the future.
- For diff function
- Tested each of four combinations of new and old files having newlines at end or not to verify the correct behavior similar to git diff with "\ No newline at end of file" token.
- Verified that content before first @@ is removed
- Verified that newlines after each @@ line are stripped out
- Manually compared diff produced for large tap-github-catalog.json change to a diff produced with git diff. Verified that the diff results in the same change set, but observed that the actual diff algorithm is slightly different when changes are ambiguous.
- Overall …
=> Kevin/2021 08 29 mw-82 fetch large patches

tap_github/__init__.py, tap_github/schemas/branches.json
Adds branches as a data source
- Verified locally that branches imported successfully from minwareco/scheduled
- (Didn't deploy since this is a small change).
=> MW-79 adding branches data source

tap_github/__init__.py
Fixes a bug where the previous raw file contents were being fetched without adjusting the file name for a rename. This replaces the new with the old file name for fetching the previous file blob and successfully mitigates the 404 error that was popping up previously.
- Ran manually with several commits that exhibited this issue. Verified that they imported the file contents successfully without getting 404s and that the data loaded successfully into the local database.
=> fixing bug with previous filename loading

tap_github/__init__.py
Fixes an issue where there were lots of warnings about "None" being an invalid timestamp.
- Ran with the changes and observed the warning disappearing.
=> fixing utf8 hook, which was causing the issue

tap_github/__init__.py, tap_github/schemas/commits.json
Stops fetching individual commit detail and file info through github's API so that we can get the import that's affected by rate limiting moving as quickly as possible. Also adds info that was omitted before about the github user name and ID of the commit author/committer.
- Ran using scheduled and inspected output file to verify that it is correct.
=> MW-86 removing commit detail and adding github user info

tap_github/__init__.py
Handles 404 on collaborators, which will occur when the user has limited access
- Re-ran command that was failing and observed that the import completed successfully after making this change.
=> gracefully handling missing collaborators

tap_github/__init__.py, tap_github/schemas/commit_files.json
This commit puts commit_files into an array for each commit instead of its own tables so that we can tell whether or not we've imported a commit that doesn't have any changes and have integrity when running downstream taps.
- See the PR description for [mwgit pr 3](https://github.com/minwareco/tap-mwgit/pull/3) -- ran locally with minwareco/scheduled and fed into mwgit and mwblame.
=> putting commit files into an array

tap_github/__init__.py, tap_github/gitlocal.py
Updates the local git to do a full mirror on the clone so that it's not necessary to do any fetches. This should also get us *all* of the commits and eliminate the need to pull anything from github's API, which has now been disabled.
- Ran on a clean temp dir for ec2sw, completed the whole import (to outfile) in 2m 25s, observed no warnings about missing commits
- Ran on existing checkout for ec2sw, completed the whole import (to outfile) in 1m 52s initially, down to about 1m 30s after optimizing parallel processing, 25s of which was just getting all of the commit lists from the heads.
=> changing git local to use mirrored clone

tap_github/__init__.py, tap_github/gitlocal.py
This commit adds paging to the git log command so that we can be more efficient, especially for long histories
- Ran this on ec2sw locally and observed a drop in the run time of the initial part of the job from 25 seconds down to 10 seconds, and verified that total number of queued commits was the same.
=> Adding paging to git log

tap_github/__init__.py, tap_github/gitlocal.py
Fixes a bug where PR bookmarks can get written out, subsequent commits fail, and then they never get loaded due to missing PR heads.
- Just going to run in production and verify that we're no longer importing all of the PRs.
=> fixing pr state issue

tap_github/__init__.py, tap_github/gitlocal.py
Eliminate a large bottleneck caused by usage of `git log` with a small page size. Simply increasing the page size to 10k reduces the processing time from 12 hours down to ~2 minutes.
Add a few log messages for ease of debugging and profiling.
- 
- 
=> Eliminate git log bottneck, add more logging 

tap_github/__init__.py
Stops writing the state after every stream and only writes it once per repo to prevent memory exhaustion in the snowflake target.
- Not tested yet, going to have to run in production and see if it fixes the issue.
=> cutting down on state writes

tap_github/__init__.py
Fixes the issue where personal repositories were failing due to 404 errors on the teams endpoint. Updated the tap to just skip data in that case.
- Re-ran tj/commander.js, which was previously failing, and confirmed that it finished successfully when writing to outfile and running locally.
=> handling 404 error on teams gracefully

tap_github/__init__.py, tap_github/schemas/commits.json
Changes the unique key for commits from SHA to ID (repo/sha) to avoid problems with forked repos not importing properly.
- Ran locally with outfile to observe that the schema and records properly updated to use the ID as the unique key for the commits stream.
=> changing unique commit key to ID

tap_github/__init__.py
Allows for 3 network retries with a simple linear back-off algorithm. The code performs a retry upon any exception that comes out of the `requests` package.
Updated the v2 `executor` to point at the commit hash for this change and ran the github tap for one repo successfully. Then, ran the repo again but without internet connectivity in order to validate the retry logic.
- 
=> Add retry logic for network failures

tap_github/__init__.py
Process the team related data only once per org. Also, only do that if the `process_globals` flag is true, which it is by default. The orchestration code will set this flag in order to optimize global data processing.
Tested in dev environment by processing multiple repos in Foreground org and verifying that global data was processed only once per GitHub org.
- 
=> Optimize global data processing

tap_github/__init__.py
Fixes a bug where teams and memberships weren't getting updated as expected, which was pretty obvious based on the output of only a few members getting added that later loop iterations were being skipped.
- Ran with JupiterOne and observed that all the members/memberships were correctly imported after making the fix.
=> removing cache check on sub-queries

tap_github/__init__.py
Add support for using '\*/\*' repository wildcard with a PAT in order to enumerate all orgs and the repos within.
Executed locally via `executor`:
* `repository` = '\*/\*' with a valid `access_token` provided. Verified that all expected orgs and repos were enumerated.
* `repository` = '\*/\*' without a valid `access_token` provided (falls back to app install auth). Verified that an exception is thrown because this is not supported. App installation auth requires to specify the org.
* `repository` = 'minwareco/\*' with a valid `access_token` provided. Verified that only the minwareco repos were enumerated.
* `repository` = 'minwareco/\*' without a valid `access_token` provided (falls back to app install auth). Verified that only the minwareco repos were enumerated.
- 
=> Add support for org wildcard

tap_github/__init__.py
Set assignee from assignees array if it is null. For some reason, the data from Github comes back this way for some issues.
- Ran against Storj data and verified that a few of the issues which previously did not have an assignee set are now populated with an assignee correctly
- 
=> Set assignee from assignees array if it is null

tap_github/__init__.py, tap_github/schemas/code_coverage.json
https://minware.atlassian.net/browse/MW-1562
Support ingestion of code coverage data from specific Github artifacts. This supports the `clover.xml` output from Jest, which contains all the information we are interested in.
First, I set up a branch in `scheduled` to produce a test coverage report with a temporary Github actions workflow: https://github.com/minwareco/scheduled/blob/feature/MW-1562-code-coverage-poc-3/.github/workflows/coverage_poc.yml
Next, I ran the new action to produce the artifact: https://github.com/minwareco/scheduled/actions/runs/5047002916
Finally, I ran the new `tap-github` code against the repository and verified correct parsing and output of all the code coverage data. The schema of this data can be seen in this PR as `tap_github/schemas/code_coverage.json`.
=> Add support for ingesting code coverage data from Github artifacts

tap_github/__init__.py, tap_github/schemas/refs.json
Uses `id` instead of `ref` as the key property to allow ensure uniqueness when multiple repositories have identical ref names.
=> Add id to refs table

tap_github/__init__.py
1. Ran tap locally and ensured that expired artifacts are not fetched
Observed error in log
```
CRITICAL HTTP-error-code: 410, URL: https://api.github.com/repos/*****/****/actions/artifacts/708238332/zip. Error: {'message': 'Artifact has expired', 'documentation_url': 'https://docs.github.com/rest/actions/artifacts#download-an-artifact'}
Traceback (most recent call last):
File "/opt/tap-github/bin/tap-github", line 8, in <module>
sys.exit(main())
File "/opt/tap-github/lib/python3.9/site-packages/singer/utils.py", line 229, in wrapped
return fnc(*args, **kwargs)
File "/opt/tap-github/lib/python3.9/site-packages/tap_github/__init__.py", line 2419, in main
do_sync(args.config, args.state, catalog)
File "/opt/tap-github/lib/python3.9/site-packages/tap_github/__init__.py", line 2377, in …
```
=> Filter artifacts that have expired so we don't try and fetch them

tap_github/__init__.py
Avoid missing commits when this is run on an empty repo.  Later, the handling of fetchedCommits will cause issues with the `since` param.  This always does a sync from `1970-01-01` to avoid these issues.
- 
=> Remove use of since because empty repos can cause a problem later

tap_github/__init__.py
Avoid overwriting state when fetching deployment status
Remove logging around deployment status
- 
=> Fix state being emptied after deployment_status

tap_github/schemas/workflow_runs.json
Email field from API returns what is in git for an email, which is not always formatted correctly.  Using format `email` makes jsonschema validation fail in some targets.
- None
- 
=> Update head_commit to be more concise and remove explicit format for email

tap_github/__init__.py
- Ran locally with org that has deployments
- Ran locally after making the changes
- Ran once pointed at snowflake
- Ran again
=> Save bookmark for github deployments

tap_github/__init__.py
- Planted unavailable repo in allRepos list
- Tested without skip_unavailable in config
- Tested with skip_unavailable in config set to false
- Tested with skip_unavailable in config set to true
=> Skip unavailable repos with config parameter

tap_github/__init__.py
MW-5524
1. Update logging to provide additional context when we run into an error making graphql queries
2. Handle getting err['type'] in a way that won't throw
I am unable to repro this locally so will test this in production.
=> update exception handling to better handle keys that might not be there

tap_github/__init__.py
Manually ran ingest for smartpension/cms using production state. Observed that the error is logged and the ingest proceeds.
=> skip the graph project v2 error

tap_github/__init__.py
This handles 422 errors when getting repositories. 
We get those errors when there are no repositories associated with the org.
I validated with Susan's test org that we got the error when there were no repositories. When she added one, the error went away. 
I then validated this change for the other orgs which received the error and the job completes without issue.
=> handle orgs without repos

tap_github/__init__.py
=> Utilize the repo_cache when fetching repo data

tap_github/__init__.py
- Generated github token
- Ran locally with reset_state and verified skip_unavailable properly skips unavailable repos and processes existing repos
=> Set auth headers before making metadata call

tap_github/schemas/issue_events.json
Not tested yet, but will run an ingest to validate after adding the fields to the database.
=> add issue type object to issue_events catalog

setup.py, tap_github/__init__.py, tap_github/schemas/commit_files_meta.json
This change allows us to process the commit files meta job. 
Ran a github ingest that completed successfully (just the source -> jsonl part).
I have validated this by running commit files meta and commit files jobs and observed that the files make it into S3.
Then I ran an s3 -> snowflake job and saw that we get the records as expected in the source schema.
```
Select * from T_7875C5067419433C84FD656541FE7F3A_GITHUB.COMMIT_FILES_META where _sdc_repository = 'myleshenderson/config';
Select * from T_7875C5067419433C84FD656541FE7F3A_GITHUB.COMMIT_FILES where _sdc_repository = 'myleshenderson/config';
```
=> implement commit only mode

tap_github/__init__.py, tests/unittests/test_rate_limit_handling.py
Update to ensure that when the reset time has already passed, we should retry immediately (sleep 0) rather than crashing with a negative sleep value.
Validated by updating unit tests and also running dev ingest for an org. The real test though will be in production.
=> fix to ensure we don't have negative values

tap_github/__init__.py, tests/unittests/test_onboarding_workflow_skip.py
Adds an `is_onboarding_complete` parameter that's used to conditionally remove workflow related streams from the selected streams when it is true.
Validated with unit tests and by running dev:ingest for an org. When`is_onboarding_complete` is not set or is `true` we ingest workflows. When set to `false`, we do not ingest workflow related records.
=> add and use is_onboarding_complete flag
