minwareco/tap-github

- tap_github/__init__.py
Fixes an issue where the state was getting screwed up due to a weird translation step that happened prior to expanding star repos.
- Actually ran it with an existing state file this time to verify that the fetched commits were found and used when importing commit files after making the fix, while they were being ignored and re-imported before.
> figured out problem that was causing invalid state

- tap_github/gitlocal.py
Fixes a bug that was causing empty repos to fail github.files import.
- Ran on empty repo before
- Ran on empty repo after, verified that it didn't fail.
> MW-396 - Fixing bug with empty repo

- tap_github/__init__.py
Add a tap stream for "repositories" that simply emits data about each repository. Supports wildcard "<org>/*" wildcard to enumerate all available repositories in the org.
See corresponding changes in the `scheduled` repo at https://github.com/minwareco/scheduled/pull/102
https://minware.atlassian.net/browse/MW-488
Executed locally within the `scheduled` repo using a file as the target output to verify correctness of each record. Tested against `minwareco/*` and `redpointops/*`
Tested using a PAT and a GitHub app key. The PAT was able to enumerate repos for both orgs because the PAT has access to both orgs, while the GitHub app key was only able to enumerate repos for `minwareco`.
- 
> Add tap stream for "repositories"

- tap_github/__init__.py
Add remaining repo properties sufficient to fully define an `integration_repository` DB record, which is inserted by `target-reposync`.
See notes in https://github.com/minwareco/scheduled/pull/105
- 
> Add more properties to the repo output records

- tap_github/gitlocal.py
> fixing hmac with same changes from azure-git

- tap_github/__init__.py
- tap_github/schemas/comments.json
- tap_github/schemas/issue_events.json
- tap_github/schemas/issues.json
Add props that we need in order to support GitHub issues as a ticket source: https://minware.atlassian.net/browse/MW-936
Executed with a branch of `scheduled` which has the same schema changes and verified that the new columns are added to the target schema. Verified that the new columns have values as expected.
Project column moves:
> Add more props to support GitHub issues as a ticket source

- tap_github/__init__.py
Support personal Github account ingest, which is slightly different than organization account ingest for certain API calls.
https://minware.atlassian.net/browse/MW-1191
Tested against `halafi` user locally while pointed at the production Postgres DB:
* Ran repo sync successfully, which populated all of the user's repos into the prod DB. They can be seen at https://www.minware.com/settings/org/halafi/repositories
* Ran github ingest successfully on a single repository (halafi/cookieconsent) to ensure that all the streams worked. The ingest output went to file and _not_ to the production Snowflake DB.
Tested against `minwareco` organization to ensure that functionality was not broken.
* Ran repo sync successfully.
* Ran ingest of `minwareco/repotest` successfully.
- 
> Support personal Github accounts

- tap_github/__init__.py
> Fix syntax error in python try catch block

- setup.py
> Lock gitlocal to latest commit

- setup.py
Use gitlocals main branch instead of a specific commit.
- 
- 
> Use gitlocal main branch

- tap_github/__init__.py
Fetch the full repository details when getting the repo meta. Fields relating to forks are not included when listing all repositories.
- 
- 
> Populate the fork names properly for github repos

- setup.py
> Update PyJWT and cryptography for security vulnerability fixes

- tap_github/__init__.py
Ignore tos errors from github.
> Ignore github terms of service errors on a repo

- tap_github/__init__.py
Proceed without failing when deployments are not available.
- 
> Allow auth failures to occur for deployments without failing job

- tap_github/__init__.py
- tap_github/schemas/deployment_statuses.json
- tap_github/schemas/deployments.json
- tap_github/schemas/workflow_run_jobs.json
- tap_github/schemas/workflow_runs.json
- tap_github/schemas/workflows.json
> Update schemas to allow null for many more fields, remove descriptions which were sometimes incorrect, make workflows optional

- tap_github/__init__.py
- Ran on-premise-agent with include, exclude, and with a hard-coded limit to one small org and my access token. Verified state and visually inspected one data file to verify correctness.
> adding exclude option

- tap_github/__init__.py
- Ran without base_url parameter and with api.github.com parameter, verified that the whole ingest ran with on-premise-agent for classic and fine-grained access tokens
- Ran with invalid parameter, verified that the tap failed
> updating api url to be a parameter

- tap_github/__init__.py
Make projects_v2 optional by ignoring insufficient scopes and forbidden errors.
- Repro'd error with a similar config to those failing in production
- Verified issue was fixed after these changes
- 
> Wrap projects v2 query in try catch to ignore auth issues

- tap_github/__init__.py
> Log better info on failure for diagnostic purposes

- tap_github/schemas/deployments.json
> Add nullability to payload schema

- tap_github/__init__.py
-  See corresponding PR in other repo.
- 
> Add graphql_url to the config

- tap_github/__init__.py
> Drastically reduce batch size to reduce memory consumption

- tap_github/__init__.py
> Handle 451 error ode when fetching a repository

- tap_github/__init__.py
- Ran against minware repo test with github-files. Verified that it ran successfully and loaded all the commits.
> updating gitlocal to use new and faster pyGit method

- tap_github/__init__.py
- tests/test_logging.py
MW-5417 - Remove token from logs
- No manual testing but I did add new tests
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
> redact token if present when logging

- tap_github/__init__.py
Experimenting with a smaller page size for projects V2. Will test in production.
> update page size

- tap_github/__init__.py
Previously if we had a bad PAT, it would try to refresh the credentials. Now, we just fail if we have a bad PAT since there's nothing that we can do.
Validated by:
1. Running this with an org which has a bad PAT and received the following:
```
CRITICAL Authentication Error: Invalid GitHub credentials.
CRITICAL If you are using a Personal Access Token (PAT), please verify it is valid and has the required permissions.
CRITICAL Error details: Invalid GitHub Personal Access Token (PAT). The token was rejected by GitHub.
[2025-02-27T19:20:04.664Z] ERROR Ingest pipeline failed with result: 1,0
```
2. Running this with an org which uses the app install and observed that things are fine.
3. Running this with an org with a known good PAT and observed that things are fine.
> fail fast and log well if we have a bad PAT

- tap_github/__init__.py
Reverts minwareco/tap-github#75 was originally made to work around a github bug which we believe to be fixed at this point.
> MW-5530 - Revert the change for MW-5524

- setup.py
Tested with https://github.com/minwareco/minware-singer-utils/pull/10
> bump version utils

- tap_github/__init__.py
Allow providing an installation id to avoid fetching all installations on each run.
> Allow installation_id to provided and avoid fetching all installations

- tap_github/__init__.py
- tap_github/schemas/repositories.json
- Ran with fetch_forks on and fetch_forks off in the config
- Validated proper results in the records
- Validated schemas are only exported a single time per run
> Add is_fork property
